### ISSUE TITLE
sadf

### ISSUE THREAD

**Issue by JanNetoLlorens** [The-Century-Scratch/Project-2-Breaking-Cats#2]
![Amily-AoV](https://user-images.githubusercontent.com/99729455/224486068-b533db56-b631-4d6e-a9a3-388c38ea9c32.jpg)
![kalashtar](https://user-images.githubusercontent.com/99729455/224486070-2d73ec81-815a-4230-af90-1581bf32d87b.jpg)

**Comment by Hekbas** [comment]
Nice pic bruh
